INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (1,'123','ADMIN');
INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (2,'123','EMPREGADO');
INSERT INTO USUARIO (ID, PASSWORD, USERNAME) VALUES (3,'123','DEPARTAMENTO');

INSERT INTO ROLE (ID, NAME) VALUES (1,'ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (2,'EMPREGADO');
INSERT INTO ROLE (ID, NAME) VALUES (3,'DEPARTAMENTO');

INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (1,1);
INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (2,2);
INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLES_ID) VALUES (3,3);








